#!/usr/bin/env bash
# MAF Environment Context
# Generated by MAF setup wizard
#
# This file provides environment detection for MAF operations.
# It sets critical environment variables that agents and scripts
# can rely on for context-aware behavior.
#
# Source this file at the start of any MAF script:
#   source "$(git rev-parse --show-toplevel)/.maf/context.sh"
#
# Environment Variables Set:
#   PROJECT_ROOT      - Git repository root directory
#   MAF_LAYOUT        - One of: hq, franchisee, legacy
#   MAF_SUBTREE_PREFIX - Path prefix for MAF files ("" for HQ, "maf" for franchisee)

set -euo pipefail

# Detect project root (git repository root)
if ! PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    echo "ERROR: Not in a git repository" >&2
    echo "MAF requires a git repository to function." >&2
    exit 1
fi

export PROJECT_ROOT

# Detect MAF layout type
#
# HQ Layout: MAF is the primary repository
#   - scripts/maf/ contains MAF scripts
#   - lib/maf/ contains MAF libraries
#   - No maf/ subtree prefix needed
#
# Franchisee Layout: MAF is consumed as a subtree
#   - maf/scripts/maf/ contains MAF scripts
#   - maf/lib/maf/ contains MAF libraries
#   - maf/ subtree prefix required
#
# Legacy Layout: Old or custom layout
#   - Fallback for repositories that don't match standard patterns

# Check for HQ or franchisee layout based on scripts/maf location
if [[ -d "$PROJECT_ROOT/scripts/maf" ]]; then
    # scripts/maf exists - could be HQ or franchisee
    if [[ -d "$PROJECT_ROOT/maf" ]]; then
        # Both exist - check if maf/ is a subtree (franchisee) or worktree (HQ)
        if [[ -f "$PROJECT_ROOT/maf/.maf-subtree-marker" ]] || \
           git -C "$PROJECT_ROOT" log --oneline -1 "$PROJECT_ROOT/maf" 2>/dev/null | grep -q "Subtree"; then
            # Franchisee: maf/ is a git subtree
            MAF_LAYOUT="franchisee"
            MAF_SUBTREE_PREFIX="maf"
        else
            # HQ: maf/ exists but is not a subtree (likely a worktree or symlink)
            MAF_LAYOUT="hq"
            MAF_SUBTREE_PREFIX=""
        fi
    else
        # Only scripts/maf exists - this is HQ layout
        MAF_LAYOUT="hq"
        MAF_SUBTREE_PREFIX=""
    fi

# Check for legacy layout (old maf repo structure)
elif [[ -d "$PROJECT_ROOT/lib/maf" ]] || [[ -d "$PROJECT_ROOT/.claude/skills" ]]; then
    MAF_LAYOUT="legacy"
    MAF_SUBTREE_PREFIX=""

# Unknown layout - this is an error
else
    echo "ERROR: Unable to detect MAF layout" >&2
    echo "" >&2
    echo "Expected one of:" >&2
    echo "  1. Franchisee: maf/scripts/maf/ exists" >&2
    echo "  2. HQ: scripts/maf/ exists (and maf/ does not)" >&2
    echo "  3. Legacy: lib/maf/ or .claude/skills/ exists" >&2
    echo "" >&2
    echo "Detected:" >&2
    echo "  PROJECT_ROOT: $PROJECT_ROOT" >&2
    echo "  maf/ exists: $([ -d "$PROJECT_ROOT/maf" ] && echo 'yes' || echo 'no')" >&2
    echo "  scripts/maf/ exists: $([ -d "$PROJECT_ROOT/scripts/maf" ] && echo 'yes' || echo 'no')" >&2
    echo "  lib/maf/ exists: $([ -d "$PROJECT_ROOT/lib/maf" ] && echo 'yes' || echo 'no')" >&2
    echo "" >&2
    echo "Please run MAF setup wizard: maf/scripts/maf/setup-maf.sh" >&2
    exit 1
fi

export MAF_LAYOUT MAF_SUBTREE_PREFIX

# Derived paths (for convenience)
#
# These paths are computed based on the detected layout.
# Scripts can use these instead of constructing paths manually.

# MAF scripts directory
MAF_SCRIPTS_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/scripts/maf"
export MAF_SCRIPTS_DIR

# MAF libraries directory
MAF_LIB_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/lib/maf"
export MAF_LIB_DIR

# MAF configuration directory (in subtree)
MAF_CONFIG_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/.maf/config"
export MAF_CONFIG_DIR

# MAF documentation directory
MAF_DOCS_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/docs"
export MAF_DOCS_DIR

# Franchisee overrides directory (outside subtree, for franchisees only)
if [[ "$MAF_LAYOUT" == "franchisee" ]]; then
    FRANCHISEE_OVERRIDE_DIR="$PROJECT_ROOT/.maf/overrides"
    FRANCHISEE_CONFIG_DIR="$PROJECT_ROOT/.maf/config"
    export FRANCHISEE_OVERRIDE_DIR FRANCHISEE_CONFIG_DIR
fi

# Response Awareness skills directory
MAF_SKILLS_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/.claude/skills"
export MAF_SKILLS_DIR

# Vendor directory (for upstream dependencies)
if [[ "$MAF_LAYOUT" == "hq" ]]; then
    VENDOR_DIR="$PROJECT_ROOT/vendor"
elif [[ "$MAF_LAYOUT" == "franchisee" ]]; then
    VENDOR_DIR="$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/vendor"
else
    VENDOR_DIR="$PROJECT_ROOT/vendor"
fi
export VENDOR_DIR

# Validation: Check that critical directories exist
#
# This ensures that the detected layout is actually valid.
# Scripts can rely on these directories existing.

case "$MAF_LAYOUT" in
    hq)
        if [[ ! -d "$MAF_SCRIPTS_DIR" ]]; then
            echo "WARNING: MAF scripts directory not found: $MAF_SCRIPTS_DIR" >&2
        fi
        ;;
    franchisee)
        if [[ ! -d "$MAF_SCRIPTS_DIR" ]]; then
            echo "WARNING: MAF scripts directory not found: $MAF_SCRIPTS_DIR" >&2
        fi
        ;;
    legacy)
        # Legacy layouts may not have all directories, so we skip validation
        ;;
esac

# MAF Version Detection
#
# Try to detect the MAF version from the VERSION file.
# This is useful for feature detection and compatibility checks.

if [[ -f "$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/VERSION" ]]; then
    MAF_VERSION="$(cat "$PROJECT_ROOT${MAF_SUBTREE_PREFIX:+/$MAF_SUBTREE_PREFIX}/VERSION")"
    export MAF_VERSION
else
    # VERSION file not found - this is okay for development versions
    MAF_VERSION="dev"
    export MAF_VERSION
fi

# Output context information (when sourced with -v or --verbose)
#
# This allows scripts to check what context was detected.
# Usage: source .maf/context.sh --verbose

if [[ "${1:-}" == "--verbose" ]] || [[ "${1:-}" == "-v" ]]; then
    cat << EOF
MAF Context Detected:
  Layout: $MAF_LAYOUT
  Subtree Prefix: $MAF_SUBTREE_PREFIX
  Project Root: $PROJECT_ROOT
  Version: $MAF_VERSION

  Paths:
    Scripts: $MAF_SCRIPTS_DIR
    Libraries: $MAF_LIB_DIR
    Config: $MAF_CONFIG_DIR
    Docs: $MAF_DOCS_DIR
    Skills: $MAF_SKILLS_DIR
    Vendor: $VENDOR_DIR
EOF
fi
