#!/usr/bin/env bash
#
# MAF Control Console - Setup Wizard
# Single blessed entry point for all MAF operations
#
# Modes:
#   1) Install  - Set up MAF in a new repo
#   2) Update   - Update MAF config after subtree pull
#   3) Doctor   - Diagnose and fix common drift issues
#   4) Reset    - Nuke and rebuild config safely
#

set -euo pipefail

# Script version
VERSION="1.0.0"

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m' # No Color

# Unicode symbols
readonly CHECK="${GREEN}✓${NC}"
readonly CROSS="${RED}✗${NC}"
readonly WARN="${YELLOW}⚠${NC}"
readonly INFO="${BLUE}ℹ${NC}"

#
# Utility Functions
#

log_info() {
    echo -e "${INFO} $*"
}

log_success() {
    echo -e "${CHECK} $*"
}

log_error() {
    echo -e "${CROSS} $*"
}

log_warn() {
    echo -e "${WARN} $*"
}

print_header() {
    local title="$1"
    echo
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║ $title"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo
}

print_box() {
    local content="$1"
    echo "┌─────────────────────────────────────────────────────────────────┐"
    echo "$content" | fold -w 65 | sed 's/^/│ │/' | sed 's/│ │/│  │/'
    echo "└─────────────────────────────────────────────────────────────────┘"
}

confirm() {
    local prompt="$1"
    local response

    while true; do
        read -rp "${prompt} [y/N]: " response
        case "$response" in
            [Yy]|[Yy][Ee][Ss]) return 0 ;;
            [Nn]|[Nn][Oo]|"") return 1 ;;
        esac
    done
}

#
# Environment Detection
#

detect_environment() {
    local project_root layout subtree_prefix

    # Get project root
    if ! project_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        log_error "Not in a git repository"
        return 1
    fi

    # Detect MAF layout
    if [[ -d "$project_root/scripts/maf" ]]; then
        # scripts/maf exists - could be HQ or franchisee
        if [[ -d "$project_root/maf" ]]; then
            # Both exist - check if maf/ is a subtree (franchisee) or worktree (HQ)
            if [[ -f "$project_root/maf/.maf-subtree-marker" ]] || \
               git -C "$project_root" log --oneline -1 "$project_root/maf" 2>/dev/null | grep -q "Subtree"; then
                # Franchisee: maf/ is a git subtree
                layout="franchisee"
                subtree_prefix="maf"
            else
                # HQ: maf/ exists but is not a subtree (likely a worktree or symlink)
                layout="hq"
                subtree_prefix=""
            fi
        else
            # Only scripts/maf exists - this is HQ layout
            layout="hq"
            subtree_prefix=""
        fi
    else
        # Legacy or unknown layout
        layout="legacy"
        subtree_prefix=""
    fi

    # Export detected values
    echo "$project_root|$layout|$subtree_prefix"
}

get_maf_version() {
    local project_root="$1"
    local subtree_prefix="$2"
    local version_file="$project_root/$subtree_prefix/VERSION"

    if [[ -f "$version_file" ]]; then
        cat "$version_file"
    else
        echo "v0.2.x"
    fi
}

#
# Configuration Management
#

generate_context_sh() {
    local project_root="$1"
    local layout="$2"
    local subtree_prefix="$3"
    local context_file="$project_root/.maf/context.sh"

    mkdir -p "$(dirname "$context_file")"

    cat > "$context_file" << EOF
#!/usr/bin/env bash
# MAF Environment Context
# Generated by MAF setup wizard on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

export PROJECT_ROOT="$project_root"
export MAF_LAYOUT="$layout"
export MAF_SUBTREE_PREFIX="$subtree_prefix"

# Derived paths
export MAF_SCRIPTS_DIR="\$PROJECT_ROOT/\${MAF_SUBTREE_PREFIX}/scripts/maf"
export MAF_LIB_DIR="\$PROJECT_ROOT/\${MAF_SUBTREE_PREFIX}/lib/maf"
export MAF_CONFIG_DIR="\$PROJECT_ROOT/.maf/config"
export MAF_DOCS_DIR="\$PROJECT_ROOT/\${MAF_SUBTREE_PREFIX}/docs"
EOF

    chmod +x "$context_file"
    log_success "Generated .maf/context.sh"
    echo "  Layout: $layout"
    echo "  Subtree prefix: '$subtree_prefix'"
    echo "  Project root: $project_root"
}

load_context() {
    local context_file="$PROJECT_ROOT/.maf/context.sh"

    if [[ -f "$context_file" ]]; then
        source "$context_file"
        return 0
    else
        return 1
    fi
}

generate_agent_topology() {
    local config_dir="$1"
    local session_name="$2"
    local project_name="$3"
    local supervisor="$4"
    local reviewer="$5"
    local imp1="$6"
    local imp2="$7"

    mkdir -p "$config_dir"

    cat > "$config_dir/agent-topology.json" << TOPOLOGY_EOF
{
  "version": "1.0",
  "session_name": "$session_name",
  "project_name": "$project_name",
  "panes": [
    {
      "name": "$supervisor",
      "role": "supervisor",
      "command": "claude"
    },
    {
      "name": "$reviewer",
      "role": "reviewer",
      "command": "claude"
    },
    {
      "name": "$imp1",
      "role": "implementor",
      "command": "claude"
    },
    {
      "name": "$imp2",
      "role": "implementor",
      "command": "claude"
    }
  ],
  "role_mappings": {
    "supervisor": "$supervisor",
    "reviewer": "$reviewer",
    "implementor_1": "$imp1",
    "implementor_2": "$imp2"
  }
}
TOPOLOGY_EOF

    log_success "Generated .maf/config/agent-topology.json"
}

generate_agents_md() {
    local project_root="$1"
    local subtree_prefix="$2"
    local project_name="$3"
    local session_name="$4"
    local supervisor="$5"
    local reviewer="$6"
    local imp1="$7"
    local imp2="$8"
    local layout="$9"

    local template_file="$project_root/$subtree_prefix/templates/AGENTS.md.template"
    local output_file="$project_root/AGENTS.md"
    local generation_date

    generation_date="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

    if [[ ! -f "$template_file" ]]; then
        log_error "Template not found: $template_file"
        return 1
    fi

    # Use sed for template substitution
    sed "s/__PROJECT_NAME__/$project_name/g" "$template_file" | \
    sed "s/__SESSION_NAME__/$session_name/g" | \
    sed "s/__SUPERVISOR__/$supervisor/g" | \
    sed "s/__REVIEWER__/$reviewer/g" | \
    sed "s/__IMP1__/$imp1/g" | \
    sed "s/__IMP2__/$imp2/g" | \
    sed "s/__MAF_LAYOUT__/$layout/g" | \
    sed "s/__MAF_SUBTREE_PREFIX__/$subtree_prefix/g" | \
    sed "s|__PROJECT_ROOT__|$project_root|g" | \
    sed "s/__GENERATION_DATE__/$generation_date/g" > "$output_file"

    log_success "Generated AGENTS.md"
}

#
# Validation Functions
#

validate_config() {
    local project_root="$1"
    local config_dir="$project_root/.maf/config"
    local topology_file="$config_dir/agent-topology.json"
    local agents_file="$project_root/AGENTS.md"
    local context_file="$project_root/.maf/context.sh"
    local errors=0

    echo
    echo "Running validation checks..."

    # Check .maf/context.sh exists
    if [[ ! -f "$context_file" ]]; then
        log_error "Missing .maf/context.sh"
        ((errors++))
    else
        # Source and validate
        if ! source "$context_file" 2>/dev/null; then
            log_error "Failed to source .maf/context.sh"
            ((errors++))
        else
            log_success "context.sh is valid"
        fi
    fi

    # Check agent-topology.json exists and is valid JSON
    if [[ ! -f "$topology_file" ]]; then
        log_error "Missing agent-topology.json"
        ((errors++))
    else
        if command -v jq &>/dev/null; then
            if jq empty "$topology_file" 2>/dev/null; then
                log_success "agent-topology.json is valid JSON"
            else
                log_error "agent-topology.json contains invalid JSON"
                ((errors++))
            fi
        else
            log_warn "jq not found - skipping JSON validation"
        fi
    fi

    # Check AGENTS.md exists
    if [[ ! -f "$agents_file" ]]; then
        log_error "Missing AGENTS.md"
        ((errors++))
    else
        log_success "AGENTS.md exists"
    fi

    # Check if scripts are executable
    local subtree_prefix="${MAF_SUBTREE_PREFIX:-}"
    local scripts_dir="$project_root/$subtree_prefix/scripts/maf"

    if [[ -d "$scripts_dir" ]]; then
        local script_count=0
        local exec_count=0

        while IFS= read -r -d '' script; do
            ((script_count++))
            if [[ -x "$script" ]]; then
                ((exec_count++))
            fi
        done < <(find "$scripts_dir" -name "*.sh" -type f -print0)

        if [[ $script_count -gt 0 ]]; then
            echo "  Scripts: $exec_count/$script_count executable"
        fi
    fi

    return $errors
}

#
# Mode 1: Install
#

mode_install() {
    print_header "MAF Setup Wizard - Install Mode"

    #### Step 1: Launch Setup Wizard
    # (Already done by print_header)

    #### Step 2: Environment Detection (Context-Awareness) ⚠️ CRITICAL
    echo "Step 2: Environment Detection (Context-Awareness)"
    echo "──────────────────────────────────────────────────"

    # Perform automatic detection
    local detection
    detection="$(detect_environment)"
    IFS='|' read -r project_root layout subtree_prefix <<< "$detection"

    echo "Detected environment:"
    echo "  Layout: $layout"
    echo "  Subtree prefix: '$subtree_prefix'"
    echo "  Project root: $project_root"
    echo

    # Generate .maf/context.sh
    echo "Generating .maf/context.sh..."

    generate_context_sh "$project_root" "$layout" "$subtree_prefix"
    echo

    # Load context for subsequent steps
    # shellcheck source=/dev/null
    source "$project_root/.maf/context.sh"

    chmod +x "$project_root/.maf/context.sh"
    echo "✓ Generated .maf/context.sh"
    echo

    #### Step 3: Interactive Configuration
    echo "Step 3: Interactive Configuration"
    echo "─────────────────────────────────"
    echo

    # Prompt for project name
    read -rp "Project name: " project_name
    if [[ -z "$project_name" ]]; then
        log_error "Project name cannot be empty"
        exit 1
    fi
    echo

    # Prompt for session name (with validation)
    while true; do
        read -rp "Session name (must be unique, not 'maf-cli'): " session_name
        if [[ "$session_name" == "maf-cli" ]]; then
            log_error "'maf-cli' is reserved. Please choose a unique name."
        elif [[ -z "$session_name" ]]; then
            log_error "Session name cannot be empty."
        else
            break
        fi
    done
    echo

    # Prompt for agent names
    read -rp "Supervisor agent name: " supervisor
    read -rp "Reviewer agent name: " reviewer
    read -rp "Implementor 1 name: " imp1
    read -rp "Implementor 2 name: " imp2
    echo

    # Validate agent names
    if [[ -z "$supervisor" || -z "$reviewer" || -z "$imp1" || -z "$imp2" ]]; then
        log_error "All agent names must be provided"
        exit 1
    fi

    # Check for duplicate names
    local names=("$supervisor" "$reviewer" "$imp1" "$imp2")
    local unique_names
    unique_names="$(printf '%s\n' "${names[@]}" | sort -u | wc -l)"
    if [[ $unique_names -ne 4 ]]; then
        log_error "Agent names must be unique"
        exit 1
    fi

    #### Step 4: Configuration Generation
    echo "Step 4: Configuration Generation"
    echo "────────────────────────────────"

    generate_agent_topology \
        "$MAF_CONFIG_DIR" \
        "$session_name" \
        "$project_name" \
        "$supervisor" \
        "$reviewer" \
        "$imp1" \
        "$imp2"
    echo

    #### Step 5: AGENTS.md Generation
    echo "Step 5: Generate AGENTS.md"
    echo "──────────────────────────"

    if ! generate_agents_md \
        "$project_root" \
        "$subtree_prefix" \
        "$project_name" \
        "$session_name" \
        "$supervisor" \
        "$reviewer" \
        "$imp1" \
        "$imp2" \
        "$layout"; then
        log_error "Failed to generate AGENTS.md"
        exit 1
    fi
    echo

    #### Step 6: Validation Gates
    echo "Step 6: Validation"
    echo "──────────────────"

    if ! validate_config "$project_root"; then
        log_error "Configuration validation failed"
        exit 1
    fi
    echo

    #### Step 7: Bootstrap (optional)
    echo "Step 7: Optional Bootstrap"
    echo "───────────────────────────"
    echo

    if confirm "Initialize agent mail and beads"; then
        # Initialize agent mail
        if command -v mcp-agent-mail &>/dev/null; then
            if mcp-agent-mail init 2>/dev/null; then
                log_success "Agent mail initialized"
            else
                log_warn "Agent mail initialization reported issues"
            fi
        else
            log_warn "mcp-agent-mail not found - skipping"
        fi

        # Initialize beads
        if command -v bead &>/dev/null; then
            if bead init 2>/dev/null; then
                log_success "Beads initialized"
            else
                log_warn "Beads initialization reported issues"
            fi
        else
            log_warn "bead command not found - skipping"
        fi
    fi
    echo

    #### Step 8: Success Confirmation
    touch "$project_root/.maf/SETUP_COMPLETE"

    print_header "MAF Setup Complete"

    echo "Next steps:"
    echo "  1. Review AGENTS.md"
    echo "  2. Run: bash $subtree_prefix/scripts/maf/spawn-agents.sh"
    echo "  3. Start working with your agents!"
    echo
}

#
# Mode 2: Update
#

mode_update() {
    print_header "MAF Setup Wizard - Update Mode"

    # Load existing context
    if ! load_context; then
        log_error "No existing MAF configuration found"
        log_info "Run 'bash setup-maf.sh' and select mode 1 (Install)"
        exit 1
    fi

    log_success "Loaded existing context"
    echo "  Layout: $MAF_LAYOUT"
    echo "  Project root: $PROJECT_ROOT"
    echo

    # Detect current MAF version
    local current_version
    current_version="$(get_maf_version "$PROJECT_ROOT" "$MAF_SUBTREE_PREFIX")"
    echo "Current MAF version: $current_version"
    echo

    # Check for major/minor version changes
    # For now, just offer to regenerate AGENTS.md from template
    echo "This mode will:"
    echo "  - Preserve existing agent names from agent-topology.json"
    echo "  - Regenerate AGENTS.md from latest template"
    echo "  - Update .maf/context.sh if needed"
    echo

    if ! confirm "Continue with update"; then
        echo "Update cancelled"
        exit 0
    fi

    # Load existing topology
    local topology_file="$PROJECT_ROOT/.maf/config/agent-topology.json"

    if [[ ! -f "$topology_file" ]]; then
        log_error "agent-topology.json not found"
        exit 1
    fi

    if ! command -v jq &>/dev/null; then
        log_error "jq is required for update mode"
        exit 1
    fi

    # Extract values from existing topology
    local session_name project_name supervisor reviewer imp1 imp2
    session_name="$(jq -r '.session_name' "$topology_file")"
    project_name="$(jq -r '.project_name' "$topology_file")"
    supervisor="$(jq -r '.role_mappings.supervisor' "$topology_file")"
    reviewer="$(jq -r '.role_mappings.reviewer' "$topology_file")"
    imp1="$(jq -r '.role_mappings.implementor_1' "$topology_file")"
    imp2="$(jq -r '.role_mappings.implementor_2' "$topology_file")"

    echo "Regenerating with existing configuration:"
    echo "  Project: $project_name"
    echo "  Session: $session_name"
    echo "  Agents: $supervisor, $reviewer, $imp1, $imp2"
    echo

    # Update context.sh
    generate_context_sh "$PROJECT_ROOT" "$MAF_LAYOUT" "$MAF_SUBTREE_PREFIX"

    # Regenerate AGENTS.md
    if ! generate_agents_md \
        "$PROJECT_ROOT" \
        "$MAF_SUBTREE_PREFIX" \
        "$project_name" \
        "$session_name" \
        "$supervisor" \
        "$reviewer" \
        "$imp1" \
        "$imp2" \
        "$MAF_LAYOUT"; then
        log_error "Failed to regenerate AGENTS.md"
        exit 1
    fi

    echo
    log_success "Update complete"
    echo "  AGENTS.md regenerated from latest template"
    echo "  Agent configuration preserved"
    echo
}

#
# Mode 3: Doctor
#

mode_doctor() {
    print_header "MAF Setup Wizard - Doctor Mode"

    echo "Running health checks..."
    echo

    local issues=0

    # Check 1: Git repository
    echo "Check 1: Git repository"
    if ! git rev-parse --git-dir &>/dev/null; then
        log_error "Not in a git repository"
        ((issues++))
    else
        log_success "Git repository detected"
    fi
    echo

    # Check 2: Environment detection
    echo "Check 2: Environment detection"
    local detection
    if detection="$(detect_environment)"; then
        IFS='|' read -r detected_root detected_layout detected_prefix <<< "$detection"
        log_success "Environment detected: $detected_layout"
        echo "  Root: $detected_root"
        echo "  Prefix: '$detected_prefix'"
    else
        log_error "Failed to detect environment"
        ((issues++))
    fi
    echo

    # Check 3: .maf/context.sh
    echo "Check 3: .maf/context.sh"
    if [[ ! -f "$detected_root/.maf/context.sh" ]]; then
        log_error "Missing .maf/context.sh"
        log_info "  Fix: Run mode 1 (Install) to generate"
        ((issues++))
    else
        if source "$detected_root/.maf/context.sh" 2>/dev/null; then
            log_success "context.sh exists and is valid"
        else
            log_error "context.sh exists but fails to source"
            ((issues++))
        fi
    fi
    echo

    # Check 4: .maf/config/agent-topology.json
    echo "Check 4: .maf/config/agent-topology.json"
    local topology_file="$detected_root/.maf/config/agent-topology.json"
    if [[ ! -f "$topology_file" ]]; then
        log_error "Missing agent-topology.json"
        ((issues++))
    else
        if command -v jq &>/dev/null; then
            if jq empty "$topology_file" 2>/dev/null; then
                log_success "agent-topology.json is valid JSON"
            else
                log_error "agent-topology.json has invalid JSON"
                ((issues++))
            fi
        else
            log_warn "jq not found - skipping JSON validation"
        fi
    fi
    echo

    # Check 5: AGENTS.md
    echo "Check 5: AGENTS.md"
    if [[ ! -f "$detected_root/AGENTS.md" ]]; then
        log_error "Missing AGENTS.md"
        log_info "  Fix: Run mode 1 (Install) or mode 2 (Update)"
        ((issues++))
    else
        log_success "AGENTS.md exists"
    fi
    echo

    # Check 6: MAF subtree health
    echo "Check 6: MAF subtree health"
    local subtree_prefix="$detected_prefix"
    local health_script="$detected_root/$subtree_prefix/scripts/maf/status/check-subtree-health.sh"

    if [[ -f "$health_script" ]]; then
        if bash "$health_script" 2>/dev/null; then
            log_success "MAF subtree is healthy"
        else
            log_warn "MAF subtree health check reported issues"
            ((issues++))
        fi
    else
        log_warn "Health check script not found"
    fi
    echo

    # Check 7: Script permissions
    echo "Check 7: Script permissions"
    local scripts_dir="$detected_root/$subtree_prefix/scripts/maf"
    if [[ -d "$scripts_dir" ]]; then
        local non_executable=0
        while IFS= read -r -d '' script; do
            if [[ ! -x "$script" ]]; then
                ((non_executable++))
                echo "  Not executable: ${script#$PROJECT_ROOT/}"
            fi
        done < <(find "$scripts_dir" -name "*.sh" -type f -print0)

        if [[ $non_executable -eq 0 ]]; then
            log_success "All shell scripts are executable"
        else
            log_warn "Found $non_executable non-executable scripts"
            echo "  Fix: chmod +x $scripts_dir/*.sh"
        fi
    else
        log_warn "Scripts directory not found"
    fi
    echo

    # Summary
    if [[ $issues -eq 0 ]]; then
        print_header "All Checks Passed"
        echo "Your MAF installation appears healthy!"
        echo
    else
        print_header "Found $issues Issue(s)"
        echo "Recommended actions:"
        echo "  - Review the warnings above"
        echo "  - Run mode 1 (Install) if setup is incomplete"
        echo "  - Run mode 4 (Reset) for a fresh start"
        echo
    fi
}

#
# Mode 4: Reset
#

mode_reset() {
    print_header "MAF Setup Wizard - Reset Mode"

    echo "⚠️  WARNING: This will destroy your MAF configuration!"
    echo
    echo "This mode will:"
    echo "  1. Stop any running agent sessions (tmux)"
    echo "  2. Backup .maf/ directory"
    echo "  3. Remove .maf/ directory"
    echo "  4. Remove AGENTS.md"
    echo "  5. Re-run install mode"
    echo

    if ! confirm "Do you want to proceed"; then
        echo "Reset cancelled"
        exit 0
    fi

    # Load context for project root
    local project_root
    if ! project_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        log_error "Not in a git repository"
        exit 1
    fi

    # Stop running agents
    echo
    echo "Step 1: Stopping agent sessions"
    echo "─────────────────────────────────"

    # Try to load session name from config
    local session_name=""
    local topology_file="$project_root/.maf/config/agent-topology.json"

    if [[ -f "$topology_file" ]] && command -v jq &>/dev/null; then
        session_name="$(jq -r '.session_name' "$topology_file" 2>/dev/null || true)"
    fi

    if [[ -n "$session_name" ]]; then
        if tmux has-session -t "$session_name" 2>/dev/null; then
            tmux kill-session -t "$session_name"
            log_success "Stopped session: $session_name"
        else
            echo "  No active tmux session found"
        fi
    else
        echo "  No session name found - skipping"
    fi

    # Backup .maf/
    echo
    echo "Step 2: Backup configuration"
    echo "────────────────────────────"

    local backup_dir=".maf.backup.$(date +%Y%m%d_%H%M%S)"
    if [[ -d "$project_root/.maf" ]]; then
        cp -a "$project_root/.maf" "$project_root/$backup_dir"
        log_success "Backed up to: $backup_dir"
    else
        echo "  No .maf/ directory to backup"
    fi

    # Remove .maf/
    echo
    echo "Step 3: Remove configuration"
    echo "────────────────────────────"

    if [[ -d "$project_root/.maf" ]]; then
        rm -rf "$project_root/.maf"
        log_success "Removed .maf/"
    fi

    # Remove AGENTS.md
    if [[ -f "$project_root/AGENTS.md" ]]; then
        rm -f "$project_root/AGENTS.md"
        log_success "Removed AGENTS.md"
    fi

    echo
    log_success "Reset complete"
    echo
    echo "Starting fresh installation..."
    echo

    # Re-run install mode
    mode_install
}

#
# Main Menu
#

show_menu() {
    echo
    print_box "           MAF Control Console v$VERSION
           Multi-Agent Framework Setup"
    echo
    echo "  Select mode:"
    echo
    echo "  1) 🔧 Install      Set up MAF in a new repo"
    echo "  2) 🔄 Update       Update MAF config after subtree pull"
    echo "  3) 🩺 Doctor       Diagnose and fix common drift issues"
    echo "  4) 💣 Reset        Nuke and rebuild config safely"
    echo "  5) 🚪 Exit"
    echo
}

main() {
    # Check if we're in a git repo
    if ! git rev-parse --git-dir &>/dev/null; then
        log_error "Not in a git repository"
        echo "MAF setup must be run from within a git repository."
        exit 1
    fi

    # Show menu
    while true; do
        show_menu
        read -rp "  Choose [1-5]: " choice
        echo

        case "$choice" in
            1)
                mode_install
                break
                ;;
            2)
                mode_update
                break
                ;;
            3)
                mode_doctor
                break
                ;;
            4)
                mode_reset
                break
                ;;
            5)
                echo "Goodbye!"
                exit 0
                ;;
            *)
                log_error "Invalid choice. Please enter 1-5."
                ;;
        esac
    done
}

# Run main function
main "$@"
